// ─── The editor ──────────────────────────────────────────────────────────────
// One sheet for creating and for changing, events and tasks alike, with every
// field the PC's own popup can set.
//
// PROGRESSIVE, NOT CROWDED. Thirteen fields in a column is a form, and a form is
// what people close. So the sheet opens on the four things almost every item
// needs — what, when, how long, which category — and the rest sit behind "More",
// which states what is currently set so nothing is hidden, only folded.
//
// NO NATIVE PICKERS, anywhere. A date wheel or a colour dialog would be a native
// module, and a native module means this app can only reach the phone as a whole
// new APK instead of over the air. Every control here is plain JavaScript, which
// is why a new field can be in the user's hands a minute after it is written.
//
// The repeat and the reminder never show their data structure. They show a
// sentence — "Every 2 weeks on Mon, Wed" — generated by tested code in
// `draft.ts`, because a rule you cannot read is a rule you cannot check.

import React, { useMemo, useState } from 'react';
import {
  Alert,
  KeyboardAvoidingView,
  Modal,
  Platform,
  Pressable,
  ScrollView,
  View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { Button, Row, Text, useTheme } from '../ui/kit';
import {
  CategoryPicker, ColourPicker, Field, Segment, Stepper, TextField, Toggle,
} from '../ui/Fields';
import { radius, space, HIT } from '../theme';
import { usePlanner } from '../state/planner';
import {
  applyCategoryDefaults,
  blankDraft,
  describeNotify,
  describeRecur,
  draftFromRecord,
  toTimeString,
  validateDraft,
  weekdayName,
  type DraftInput,
  type DraftProblem,
} from '../lib/draft';
import { SWATCH_BASE_HEX } from '../lib/gcalColor';
// The engine's own wording and presets, never a second copy: a duplicate had
// the sign backwards, so a reminder labelled "before" fired after.
import { offsetLabel, OFFSET_PRESETS_TIMED } from '../lib/notifications';
import { addDays, ymd } from '../lib/agenda';
import { GENERAL_LIST_ID, resolveListId, type TaskList } from '../lib/taskLists';
import { ListChips } from '../ui/ListChips';
import type { Recurrence, RecurFreq, Weekday } from '../lib/recurrence';
import type { SyncStore } from '../lib/sync';

export interface EditorTarget {
  store: 'events' | 'tasks';
  /** Absent when creating. */
  id?: string;
  date: string;
  /**
   * Which task list a NEW task starts on. Set by the Tasks screen when a list is
   * being viewed, because adding something while looking at one list and having
   * it land somewhere else is the surprise that makes lists feel unreliable.
   */
  listId?: string;
  /**
   * Fields a gesture already decided, applied over the blank draft.
   *
   * Dragging a stretch of the grid, or sweeping days in the month view, IS the
   * answer to "when": the sheet must open already holding it. Opening on the
   * next round half hour after the user has just drawn 9:15 to 10:00 with their
   * thumb would throw the gesture away and make it look decorative.
   *
   * Only applied when creating. An existing item's own record always wins.
   */
  prefill?: Partial<DraftInput>;
}

const SWATCHES = Object.entries(SWATCH_BASE_HEX).map(([key, hex]) => ({ key, hex }));

export function Editor({ target, onClose }: {
  target: EditorTarget | null;
  onClose: () => void;
}) {
  return (
    <Modal
      visible={target !== null}
      animationType="slide"
      transparent
      onRequestClose={onClose}
      statusBarTranslucent
    >
      {target ? <Sheet target={target} onClose={onClose} /> : null}
    </Modal>
  );
}

function Sheet({ target, onClose }: { target: EditorTarget; onClose: () => void }) {
  const p = useTheme();
  const insets = useSafeAreaInsets();
  const {
    events, tasks, saveDraft, removeItem, edit, categories, interval, taskLists,
  } = usePlanner();

  const existing = useMemo(() => {
    if (!target.id) return undefined;
    const store = target.store === 'events' ? events() : tasks();
    return store[target.id];
  }, [target, events, tasks]);

  const [store, setStore] = useState<'events' | 'tasks'>(target.store);
  const [draft, setDraft] = useState<DraftInput>(() => (
    existing
      ? draftFromRecord(existing, target.store, target.date)
      : {
        // Category defaults first, then the gesture, so a drag's own times are
        // never overwritten by the category's default duration.
        ...(target.store === 'events'
          ? withDefaultCategory(blankDraft(target.date, new Date().getHours() * 60 + new Date().getMinutes()), categories)
          : blankDraft(target.date, new Date().getHours() * 60 + new Date().getMinutes())
        ),
        ...(target.prefill ?? {}),
      }
  ));
  const [problems, setProblems] = useState<DraftProblem[]>([]);
  const [busy, setBusy] = useState(false);
  const [more, setMore] = useState(false);

  const lists = useMemo<TaskList[]>(() => (
    (taskLists as any[])
      .filter(l => l && typeof l === 'object' && typeof l.id === 'string')
      .map(l => ({ id: l.id, name: String(l.name ?? 'Untitled'), color: String(l.color ?? '') }))
  ), [taskLists]);

  /**
   * Which list this task is filed on.
   *
   * Kept beside the draft rather than inside it: `DraftInput` is the shared,
   * tested shape both halves of the planner build records from, and a field only
   * the phone's task form knows about does not belong in it. It is written as
   * its own edit after the save instead, which the per-field sync layer merges
   * exactly the same way.
   */
  const existingListId = typeof existing?.listId === 'string' ? existing.listId : undefined;
  const [listId, setListId] = useState<string | undefined>(existingListId ?? target.listId);

  const isNew = !target.id;
  const set = (patch: Partial<DraftInput>) => setDraft(d => ({ ...d, ...patch }));
  const problemFor = (f: DraftProblem['field']) => problems.find(x => x.field === f)?.message;

  const category = categories.find((c: any) => c.id === draft.categoryId);

  const save = async () => {
    const found = validateDraft(draft);
    setProblems(found);
    if (found.length > 0) return;
    setBusy(true);
    try {
      const id = await saveDraft(store as SyncStore, draft, target.id);
      if (store === 'tasks' && lists.length > 0 && listId !== existingListId) {
        // General is the ABSENCE of a list, so choosing it CLEARS the field
        // rather than storing the word: every task written before lists existed
        // is on General by having no `listId` at all, and the two have to mean
        // the same thing or the same tasks would answer to two different ids.
        await edit('tasks', id, {
          listId: !listId || listId === GENERAL_LIST_ID ? undefined : listId,
        });
      }
      onClose();
    } catch (err) {
      Alert.alert('Could not save', err instanceof Error ? err.message : String(err));
      setBusy(false);
    }
  };

  const confirmDelete = () => {
    Alert.alert(
      draft.recur ? 'Delete the whole series?' : 'Delete this?',
      draft.recur
        ? 'Every occurrence will go, on this phone and on your PC.'
        : 'It will be removed from this phone and from your PC.',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: () => void (async () => {
            try {
              await removeItem(target.store as SyncStore, target.id!);
              onClose();
            } catch (err) {
              Alert.alert('Could not delete', err instanceof Error ? err.message : String(err));
            }
          })(),
        },
      ],
    );
  };

  return (
    <View style={{ flex: 1, backgroundColor: p.scrim, justifyContent: 'flex-end' }}>
      <Pressable style={{ flex: 1 }} onPress={onClose} accessibilityLabel="Close" />

      <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
        <View style={{
          backgroundColor: p.surface,
          borderTopLeftRadius: radius.lg,
          borderTopRightRadius: radius.lg,
          borderTopWidth: 1,
          borderColor: p.line,
          maxHeight: '92%',
        }}>
          <View style={{ alignItems: 'center', paddingTop: space.sm }}>
            <View style={{ width: 40, height: 4, borderRadius: 2, backgroundColor: p.line }} />
          </View>

          <ScrollView
            contentContainerStyle={{
              padding: space.lg,
              paddingBottom: insets.bottom + space.xl,
              gap: space.lg,
            }}
            keyboardShouldPersistTaps="handled"
          >
            <Row style={{ justifyContent: 'space-between', alignItems: 'center' }}>
              <Text variant="display">{isNew ? 'New' : 'Edit'}</Text>
              {!isNew && draft.recur ? (
                <Text variant="caption" tone="faint">↻ part of a series</Text>
              ) : null}
            </Row>

            {isNew ? (
              <Segment
                options={[{ key: 'events', label: 'Event' }, { key: 'tasks', label: 'Task' }]}
                value={store}
                onChange={next => {
                  setStore(next);
                  // A task has no end time; leaving one set would be written and
                  // then quietly ignored.
                  if (next === 'tasks') set({ endMin: null, daysSpan: undefined });
                }}
              />
            ) : null}

            <Field label={store === 'events' ? 'What is it' : 'What needs doing'}>
              <TextField
                value={draft.title}
                onChange={t => set({ title: t })}
                placeholder={store === 'events' ? 'Physics lecture' : 'Take the bins out'}
                autoFocus={isNew}
                invalid={Boolean(problemFor('title'))}
              />
              {problemFor('title') ? (
                <Text variant="caption" tone="danger">{problemFor('title')}</Text>
              ) : null}
            </Field>

            <Field label="Day">
              <DateStrip value={draft.date} onChange={date => set({ date })} />
            </Field>

            <Field label="Time">
              <Toggle
                label="All day"
                hint={draft.allDay ? 'No particular time' : undefined}
                value={draft.allDay}
                onChange={allDay => set({
                  allDay,
                  startMin: allDay ? draft.startMin : (draft.startMin ?? 9 * 60),
                  endMin: allDay ? draft.endMin : (draft.endMin ?? (draft.startMin ?? 9 * 60) + 60),
                })}
              />

              {!draft.allDay ? (
                <View style={{ gap: space.sm }}>
                  <TimeRow
                    label="Starts"
                    step={interval}
                    minutes={draft.startMin}
                    onChange={m => set({
                      startMin: m,
                      endMin: draft.endMin !== null && m !== null && draft.endMin <= m
                        ? m + 60 : draft.endMin,
                    })}
                  />
                  {store === 'events' ? (
                    <TimeRow
                      label="Ends"
                      step={interval}
                      minutes={draft.endMin}
                      onChange={m => set({ endMin: m })}
                      clearable
                    />
                  ) : null}
                </View>
              ) : store === 'events' ? (
                <Row style={{ alignItems: 'center', gap: space.md }}>
                  <Text variant="body" tone="soft" style={{ flex: 1 }}>Covers</Text>
                  <Stepper
                    value={draft.daysSpan ?? 1}
                    min={1}
                    max={30}
                    onChange={n => set({ daysSpan: n })}
                    format={n => (n === 1 ? '1 day' : `${n} days`)}
                  />
                </Row>
              ) : null}

              {problemFor('time') ? (
                <Text variant="caption" tone="danger">{problemFor('time')}</Text>
              ) : null}
            </Field>

            {store === 'events' ? (
              <Field label="Category">
                <CategoryPicker
                  value={draft.categoryId}
                  onChange={id => setDraft(d => (
                    // Defaults only when composing. On an edit, choosing a
                    // category must not snap a 90-minute meeting back to 60.
                    isNew
                      ? applyCategoryDefaults(d, categories.find((c: any) => c.id === id))
                      : { ...d, categoryId: id }
                  ))}
                  categories={categories as any}
                />
              </Field>
            ) : null}

            {store === 'tasks' && lists.length > 0 ? (
              <Field label="List" hint="Which part of the board it sits on">
                <ListChips
                  options={lists}
                  value={resolveListId(listId, lists)}
                  onChange={next => setListId(next ?? undefined)}
                />
              </Field>
            ) : null}

            {/* ── Everything else, folded but stated ── */}
            <Pressable
              onPress={() => setMore(v => !v)}
              style={{ paddingVertical: space.sm }}
            >
              <Row style={{ justifyContent: 'space-between', alignItems: 'center' }}>
                <Text variant="bodyStrong" tone="accent">{more ? 'Less' : 'More'}</Text>
                <Text variant="caption" tone="faint" numberOfLines={1} style={{ flexShrink: 1, textAlign: 'right' }}>
                  {more ? '' : `${describeRecur(draft.recur)} · ${describeNotify(draft.notify)}`}
                </Text>
              </Row>
            </Pressable>

            {more ? (
              <View style={{ gap: space.lg }}>
                <Field label="Repeat" hint={describeRecur(draft.recur)}>
                  <RepeatEditor
                    value={draft.recur}
                    date={draft.date}
                    onChange={recur => set({ recur })}
                  />
                </Field>

                <Field label="Reminder" hint={describeNotify(draft.notify)}>
                  <ReminderEditor value={draft.notify} onChange={notify => set({ notify })} />
                </Field>

                {!draft.categoryId ? (
                  <Field label="Colour">
                    <ColourPicker
                      value={draft.colour}
                      onChange={colour => set({ colour })}
                      swatches={SWATCHES}
                    />
                  </Field>
                ) : (
                  <Field label="Colour">
                    <Row gap={space.sm} style={{ alignItems: 'center' }}>
                      <View style={{
                        width: 14, height: 14, borderRadius: 7,
                        backgroundColor: (category as any)?.color ?? p.accent,
                      }} />
                      <Text variant="caption" tone="faint">
                        From “{(category as any)?.name ?? 'category'}”
                      </Text>
                    </Row>
                  </Field>
                )}

                <Field label="Notes">
                  <TextField
                    value={draft.notes ?? ''}
                    onChange={t => set({ notes: t })}
                    placeholder="Anything worth remembering"
                    multiline
                  />
                </Field>

                {store === 'events' ? (
                  <Field label="Behaviour">
                    <Toggle
                      label="No checkbox"
                      hint="A reference point, not something to tick off"
                      value={draft.noCheckbox ?? false}
                      onChange={v => set({ noCheckbox: v })}
                    />
                    <Toggle
                      label="No duration"
                      hint="A moment rather than a span"
                      value={draft.noDuration ?? false}
                      onChange={v => set({ noDuration: v })}
                    />
                    {draft.recur ? (
                      <Toggle
                        label="Edits apply to the whole series"
                        hint={draft.locked
                          ? 'Changing one occurrence changes them all'
                          : 'Changing one occurrence splits it out on its own'}
                        value={draft.locked ?? false}
                        onChange={v => set({ locked: v })}
                      />
                    ) : null}
                  </Field>
                ) : null}
              </View>
            ) : null}

            <Row gap={space.sm}>
              <Button label="Cancel" variant="secondary" onPress={onClose} style={{ flex: 1 }} />
              <Button
                label={isNew ? 'Add' : 'Save'}
                onPress={() => void save()}
                busy={busy}
                style={{ flex: 2 }}
              />
            </Row>

            {!isNew ? (
              <View style={{ gap: space.sm, paddingTop: space.sm }}>
                <View style={{ height: 1, backgroundColor: p.line }} />
                <Button label="Delete" variant="danger" onPress={confirmDelete} />
              </View>
            ) : null}
          </ScrollView>
        </View>
      </KeyboardAvoidingView>
    </View>
  );
}

/** A new item starts in the category the user marked as their default. */
function withDefaultCategory(input: DraftInput, categories: any[]): DraftInput {
  const preferred = categories?.find?.((c: any) => c?.isDefault);
  return preferred ? applyCategoryDefaults(input, preferred) : input;
}

// ─── Repeat ──────────────────────────────────────────────────────────────────

const FREQS: { key: RecurFreq; label: string }[] = [
  { key: 'daily', label: 'Day' },
  { key: 'weekly', label: 'Week' },
  { key: 'monthly', label: 'Month' },
  { key: 'yearly', label: 'Year' },
];

function RepeatEditor({ value, date, onChange }: {
  value: Recurrence | undefined;
  date: string;
  onChange: (next: Recurrence | undefined) => void;
}) {
  const p = useTheme();
  const on = Boolean(value);

  const set = (patch: Partial<Recurrence>) =>
    onChange({ freq: 'weekly', interval: 1, ...value, ...patch } as Recurrence);

  const endKind: 'never' | 'until' | 'count' =
    !value?.end ? 'never' : ('until' in value.end ? 'until' : 'count');

  return (
    <View style={{ gap: space.md }}>
      <Toggle
        label="Repeats"
        value={on}
        onChange={next => onChange(next ? { freq: 'weekly', interval: 1 } : undefined)}
      />

      {on && value ? (
        <View style={{ gap: space.md }}>
          <Row style={{ alignItems: 'center', gap: space.md }}>
            <Text variant="body" tone="soft">Every</Text>
            <Stepper
              value={Math.max(1, value.interval || 1)}
              min={1}
              max={52}
              onChange={n => set({ interval: n })}
            />
          </Row>

          <Segment
            options={FREQS}
            value={value.freq}
            onChange={freq => set({
              freq,
              // Weekday choices only mean anything for a weekly rule; carrying
              // them onto a monthly one would store a rule nothing can read.
              byWeekday: freq === 'weekly' ? value.byWeekday : undefined,
            })}
          />

          {value.freq === 'weekly' ? (
            <WeekdayPicker
              value={value.byWeekday ?? []}
              onChange={byWeekday => set({ byWeekday: byWeekday.length ? byWeekday : undefined })}
            />
          ) : null}

          <View style={{ gap: space.sm }}>
            <Segment
              options={[
                { key: 'never', label: 'Forever' },
                { key: 'until', label: 'Until' },
                { key: 'count', label: 'Times' },
              ]}
              value={endKind}
              onChange={kind => {
                if (kind === 'never') return set({ end: undefined });
                if (kind === 'count') return set({ end: { count: 10 } });
                return set({ end: { until: addDays(date, 7 * 12) } });
              }}
            />

            {endKind === 'count' && value.end && 'count' in value.end ? (
              <Stepper
                value={value.end.count}
                min={1}
                max={365}
                onChange={n => set({ end: { count: n } })}
                format={n => `${n} time${n === 1 ? '' : 's'}`}
              />
            ) : null}

            {endKind === 'until' && value.end && 'until' in value.end ? (
              <DateStrip
                value={value.end.until}
                onChange={until => set({ end: { until } })}
                from={date}
                days={28}
              />
            ) : null}
          </View>
        </View>
      ) : null}
    </View>
  );
}

function WeekdayPicker({ value, onChange }: {
  value: Weekday[]; onChange: (next: Weekday[]) => void;
}) {
  const p = useTheme();
  const days: Weekday[] = [0, 1, 2, 3, 4, 5, 6];

  return (
    <Row gap={space.xs}>
      {days.map(d => {
        const on = value.includes(d);
        return (
          <Pressable
            key={d}
            onPress={() => onChange(on ? value.filter(x => x !== d) : [...value, d])}
            accessibilityRole="button"
            accessibilityLabel={weekdayName(d)}
            accessibilityState={{ selected: on }}
            style={{
              flex: 1, height: 40,
              alignItems: 'center', justifyContent: 'center',
              borderRadius: radius.sm,
              backgroundColor: on ? p.accent : p.surfaceAlt,
              borderWidth: 1,
              borderColor: on ? p.accent : p.line,
            }}
          >
            <Text
              variant="caption"
              style={{ color: on ? p.accentInk : p.inkSoft, fontWeight: '700' }}
            >
              {weekdayName(d).slice(0, 1)}
            </Text>
          </Pressable>
        );
      })}
    </Row>
  );
}

// ─── Reminder ────────────────────────────────────────────────────────────────

function ReminderEditor({ value, onChange }: {
  value: any; onChange: (next: any) => void;
}) {
  const p = useTheme();

  const mode: 'default' | 'off' | 'custom' =
    !value ? 'default' : (value.enabled === false ? 'off' : 'custom');

  const rules: { id: string; offsetMin: number }[] = value?.rules ?? [];

  return (
    <View style={{ gap: space.md }}>
      <Segment
        options={[
          { key: 'default', label: 'Default' },
          { key: 'off', label: 'Off' },
          { key: 'custom', label: 'Custom' },
        ]}
        value={mode}
        onChange={next => {
          // ABSENT means inherit — from the category, then the global default.
          // That is why an item created before reminders existed still gets
          // them, so "Default" must clear the field rather than write a copy.
          if (next === 'default') return onChange(undefined);
          if (next === 'off') return onChange({ enabled: false, rules: [], priority: 'normal' });
          return onChange({
            enabled: true,
            rules: [{ id: 'r0', offsetMin: 0 }],
            priority: value?.priority ?? 'normal',
          });
        }}
      />

      {mode === 'default' ? (
        <Text variant="caption" tone="faint">
          Follows the category, or your global setting if it has none.
        </Text>
      ) : null}

      {mode === 'custom' ? (
        <View style={{ gap: space.sm }}>
          {rules.map((rule, i) => (
            <Row key={rule.id ?? i} gap={space.sm} style={{ alignItems: 'center' }}>
              <View style={{ flex: 1 }}>
                <OffsetPicker
                  value={rule.offsetMin}
                  onChange={offsetMin => onChange({
                    ...value,
                    rules: rules.map((r, j) => (j === i ? { ...r, offsetMin } : r)),
                  })}
                />
              </View>
              {rules.length > 1 ? (
                <Pressable
                  onPress={() => onChange({ ...value, rules: rules.filter((_, j) => j !== i) })}
                  hitSlop={space.sm}
                  accessibilityLabel="Remove this reminder"
                  style={{ width: 32, height: 32, alignItems: 'center', justifyContent: 'center' }}
                >
                  <Text variant="body" tone="faint">✕</Text>
                </Pressable>
              ) : null}
            </Row>
          ))}

          {rules.length < 4 ? (
            <Pressable
              onPress={() => onChange({
                ...value,
                rules: [...rules, { id: `r${Date.now()}`, offsetMin: -15 }],
              })}
              style={{ paddingVertical: space.sm }}
            >
              <Text variant="caption" tone="accent">+ Another reminder</Text>
            </Pressable>
          ) : null}

          <Toggle
            label="Urgent"
            hint="Keeps alerting until you deal with it"
            value={value?.priority === 'critical'}
            onChange={v => onChange({ ...value, priority: v ? 'critical' : 'normal' })}
          />
        </View>
      ) : null}
    </View>
  );
}

function OffsetPicker({ value, onChange }: {
  value: number; onChange: (next: number) => void;
}) {
  const p = useTheme();
  return (
    <ScrollView
      horizontal
      showsHorizontalScrollIndicator={false}
      contentContainerStyle={{ gap: space.xs, paddingRight: space.lg }}
    >
      {OFFSET_PRESETS_TIMED.map(off => {
        const on = off === value;
        return (
          <Pressable
            key={off}
            onPress={() => onChange(off)}
            accessibilityRole="button"
            accessibilityState={{ selected: on }}
            style={{
              paddingHorizontal: space.md, height: 36,
              alignItems: 'center', justifyContent: 'center',
              borderRadius: radius.pill,
              backgroundColor: on ? p.accentSoft : p.surfaceAlt,
              borderWidth: 1, borderColor: on ? p.accent : p.line,
            }}
          >
            <Text variant="caption" tone={on ? 'accent' : 'soft'}>
              {offsetLabel(off)}
            </Text>
          </Pressable>
        );
      })}
    </ScrollView>
  );
}

// ─── Time and date ───────────────────────────────────────────────────────────

function TimeRow({ label, minutes, onChange, clearable, step = 15 }: {
  label: string;
  minutes: number | null;
  onChange: (next: number | null) => void;
  clearable?: boolean;
  /** The snap interval, from this device's settings. */
  step?: number;
}) {
  const p = useTheme();

  const nudge = (delta: number) => {
    const base = minutes ?? 9 * 60;
    // Snapped to the interval, not merely moved by it: a time of 09:07 nudged by
    // fifteen should land on 09:15, not 09:22. Otherwise a single off-grid value
    // keeps every later step off-grid too.
    const raw = base + delta;
    const snapped = delta > 0
      ? Math.ceil(raw / step) * step
      : Math.floor(raw / step) * step;
    onChange(((snapped % 1440) + 1440) % 1440);
  };

  return (
    <Row style={{ alignItems: 'center', justifyContent: 'space-between' }}>
      <Text variant="body" tone="soft" style={{ width: 58 }}>{label}</Text>

      <Row gap={space.xs} style={{ alignItems: 'center' }}>
        <Step label="−" onPress={() => nudge(-step)} onLongPress={() => nudge(-60)} />
        <Pressable
          onPress={() => (minutes === null ? onChange(9 * 60) : undefined)}
          style={{
            minWidth: 88, height: HIT,
            paddingHorizontal: space.md,
            borderRadius: radius.md,
            borderWidth: 1, borderColor: p.line,
            backgroundColor: p.surfaceAlt,
            alignItems: 'center', justifyContent: 'center',
          }}
        >
          <Text variant="bodyStrong" tone={minutes === null ? 'faint' : 'ink'}>
            {minutes === null ? 'None' : toTimeString(minutes)}
          </Text>
        </Pressable>
        <Step label="+" onPress={() => nudge(step)} onLongPress={() => nudge(60)} />

        {clearable ? (
          <Pressable
            onPress={() => onChange(minutes === null ? 10 * 60 : null)}
            hitSlop={space.sm}
            style={{ paddingHorizontal: space.sm, height: HIT, justifyContent: 'center' }}
          >
            <Text variant="caption" tone="accent">{minutes === null ? 'Set' : 'Clear'}</Text>
          </Pressable>
        ) : null}
      </Row>
    </Row>
  );
}

function Step({ label, onPress, onLongPress }: {
  label: string; onPress: () => void; onLongPress: () => void;
}) {
  const p = useTheme();
  return (
    <Pressable
      onPress={onPress}
      onLongPress={onLongPress}
      delayLongPress={300}
      accessibilityRole="button"
      accessibilityLabel={label === '+' ? 'Later' : 'Earlier'}
      style={({ pressed }) => ({
        width: 42, height: HIT,
        borderRadius: radius.md,
        alignItems: 'center', justifyContent: 'center',
        backgroundColor: pressed ? p.accentSoft : p.surfaceAlt,
        borderWidth: 1, borderColor: p.line,
      })}
    >
      <Text variant="title" tone="soft">{label}</Text>
    </Pressable>
  );
}

function DateStrip({ value, onChange, from, days = 14 }: {
  value: string;
  onChange: (date: string) => void;
  from?: string;
  days?: number;
}) {
  const p = useTheme();
  const today = ymd(new Date());
  const start = from ?? today;
  /**
   * The days on offer, and always the one already chosen.
   *
   * The strip runs a fixed number of days from `from`, which is fine for a
   * fresh rule but wrong for an existing one: a repeat that ends in two years
   * had its own date sitting outside the window, so the strip showed nothing
   * selected and the date read as unset. It is appended when it falls outside,
   * so what is stored is always visible and always shown as chosen.
   */
  const list = useMemo(() => {
    const days_ = Array.from({ length: days }, (_, i) => addDays(start, i));
    if (value && !days_.includes(value)) {
      days_.push(value);
      days_.sort();
    }
    return days_;
  }, [start, days, value]);

  return (
    <ScrollView
      horizontal
      showsHorizontalScrollIndicator={false}
      contentContainerStyle={{ gap: space.xs, paddingRight: space.lg }}
    >
      {list.map(date => {
        const on = date === value;
        const d = new Date(`${date}T00:00:00`);
        return (
          <Pressable
            key={date}
            onPress={() => onChange(date)}
            accessibilityRole="button"
            accessibilityState={{ selected: on }}
            style={{
              minWidth: 54, paddingVertical: space.sm, paddingHorizontal: space.sm,
              borderRadius: radius.md, alignItems: 'center', gap: 1,
              backgroundColor: on ? p.accentSoft : p.surfaceAlt,
              borderWidth: 1, borderColor: on ? p.accent : p.line,
            }}
          >
            <Text variant="caption" tone={on ? 'accent' : 'faint'} style={{ fontSize: 11 }}>
              {d.toLocaleDateString(undefined, { weekday: 'short' })}
            </Text>
            <Text variant="bodyStrong" tone={on ? 'accent' : 'ink'}>{d.getDate()}</Text>
            <Text variant="caption" tone={on ? 'accent' : 'faint'} style={{ fontSize: 10 }}>
              {date === today ? 'today' : d.toLocaleDateString(undefined, { month: 'short' })}
            </Text>
          </Pressable>
        );
      })}
    </ScrollView>
  );
}
