// ─── The editor ──────────────────────────────────────────────────────────────
// One sheet for creating and for changing, events and tasks alike, with every
// field the PC's own popup can set.
//
// PROGRESSIVE, NOT CROWDED. Thirteen fields in a column is a form, and a form is
// what people close. So the sheet opens on the four things almost every item
// needs — what, when, how long, which category — and the rest sit behind "More",
// which states what is currently set so nothing is hidden, only folded.
//
// NO NATIVE PICKERS, anywhere. A date wheel or a colour dialog would be a native
// module, and a native module means this app can only reach the phone as a whole
// new APK instead of over the air. Every control here is plain JavaScript, which
// is why a new field can be in the user's hands a minute after it is written.
//
// The repeat and the reminder never show their data structure. They show a
// sentence — "Every 2 weeks on Mon, Wed" — generated by tested code in
// `draft.ts`, because a rule you cannot read is a rule you cannot check.

import React, { useMemo, useState } from 'react';
import {
  Alert,
  KeyboardAvoidingView,
  Modal,
  Pressable,
  ScrollView,
  View,
  StyleSheet,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { Button, Row, Text, useTheme } from '../ui/kit';
import {
  CategoryPicker, ColourPicker, Field, Segment, Stepper, TextField, Toggle,
} from '../ui/Fields';
import { HIT, PRESSED, PRESS_DELAY, clearNav, radius, space } from '../theme';
import { usePlanner } from '../state/planner';
import {
  applyCategoryDefaults,
  blankDraft,
  blankTaskDraft,
  describeNotify,
  describeRecur,
  draftFromRecord,
  toTimeString,
  validateDraft,
  weekdayName,
  type DraftInput,
  type DraftProblem,
} from '../lib/draft';
import { SWATCH_BASE_HEX } from '../lib/gcalColor';
// The engine's own wording and presets, never a second copy: a duplicate had
// the sign backwards, so a reminder labelled "before" fired after.
import { offsetLabel, OFFSET_PRESETS_TIMED } from '../lib/notifications';
import { addDays, ymd } from '../lib/agenda';
import { GENERAL_LIST_ID, resolveListId, type TaskList } from '../lib/taskLists';
import { ListChips } from '../ui/ListChips';
import type { Recurrence, RecurFreq, Weekday } from '../lib/recurrence';
import type { SyncStore } from '../lib/sync';

export interface EditorTarget {
  store: 'events' | 'tasks';
  /** Absent when creating. */
  id?: string;
  date: string;
  /**
   * Which task list a NEW task starts on. Set by the Tasks screen when a list is
   * being viewed, because adding something while looking at one list and having
   * it land somewhere else is the surprise that makes lists feel unreliable.
   */
  listId?: string;
  /**
   * Fields a gesture already decided, applied over the blank draft.
   *
   * Dragging a stretch of the grid, or sweeping days in the month view, IS the
   * answer to "when": the sheet must open already holding it. Opening on the
   * next round half hour after the user has just drawn 9:15 to 10:00 with their
   * thumb would throw the gesture away and make it look decorative.
   *
   * Only applied when creating. An existing item's own record always wins.
   */
  prefill?: Partial<DraftInput>;
}

const SWATCHES = Object.entries(SWATCH_BASE_HEX).map(([key, hex]) => ({ key, hex }));

export function Editor({ target, onClose }: {
  target: EditorTarget | null;
  onClose: () => void;
}) {
  return (
    <Modal
      visible={target !== null}
      animationType="slide"
      transparent
      onRequestClose={onClose}
      statusBarTranslucent
      // Under the navigation bar as well, not just the status bar.
      //
      // THE STRIP AT THE BOTTOM OF EVERY SHEET. Without this the modal's
      // window stops above the system navigation area, so the sheet ended
      // short and the app behind it -- the tab bar -- showed through in the
      // band below, looking like the sheet had been cropped. Each sheet
      // already pads itself by `insets.bottom`, so covering that area is what
      // makes the padding mean something instead of being doubled by a gap.
      //
      // React Native requires `statusBarTranslucent` alongside it and warns in
      // dev if it is missing, which is why the two always appear together.
      navigationBarTranslucent
    >
      {target ? <Sheet target={target} onClose={onClose} /> : null}
    </Modal>
  );
}

function Sheet({ target, onClose }: { target: EditorTarget; onClose: () => void }) {
  const p = useTheme();
  const insets = useSafeAreaInsets();
  const {
    events, tasks, saveDraft, removeItem, edit, categories, interval, taskLists,
  } = usePlanner();

  const existing = useMemo(() => {
    if (!target.id) return undefined;
    const store = target.store === 'events' ? events() : tasks();
    return store[target.id];
  }, [target, events, tasks]);

  const [store, setStore] = useState<'events' | 'tasks'>(target.store);
  const [draft, setDraft] = useState<DraftInput>(() => (
    existing
      ? draftFromRecord(existing, target.store, target.date)
      : {
        // Category defaults first, then the gesture, so a drag's own times are
        // never overwritten by the category's default duration.
        ...(target.store === 'events'
          ? withDefaultCategory(blankDraft(target.date, new Date().getHours() * 60 + new Date().getMinutes()), categories)
          // A NEW TASK IS UNDATED AND ALL-DAY, which is one decision said
          // twice: a task is something to get done, not something that happens
          // at 14:15 on Wednesday. The rule lives in `draft.ts` rather than
          // here because the PC starts a new task the same way and the two
          // write into the same store. The date it still carries is only the
          // fallback for choosing a day afterwards.
          : blankTaskDraft(target.date, new Date().getHours() * 60 + new Date().getMinutes())
        ),
        // Last, so a gesture that DID name a time still wins.
        ...(target.prefill ?? {}),
      }
  ));
  const [problems, setProblems] = useState<DraftProblem[]>([]);
  const [busy, setBusy] = useState(false);
  const [more, setMore] = useState(false);

  const lists = useMemo<TaskList[]>(() => (
    (taskLists as any[])
      .filter(l => l && typeof l === 'object' && typeof l.id === 'string')
      .map(l => ({ id: l.id, name: String(l.name ?? 'Untitled'), color: String(l.color ?? '') }))
  ), [taskLists]);

  /**
   * Which list this task is filed on.
   *
   * Kept beside the draft rather than inside it: `DraftInput` is the shared,
   * tested shape both halves of the planner build records from, and a field only
   * the phone's task form knows about does not belong in it. It is written as
   * its own edit after the save instead, which the per-field sync layer merges
   * exactly the same way.
   */
  const existingListId = typeof existing?.listId === 'string' ? existing.listId : undefined;
  const [listId, setListId] = useState<string | undefined>(existingListId ?? target.listId);

  const isNew = !target.id;
  const set = (patch: Partial<DraftInput>) => setDraft(d => ({ ...d, ...patch }));
  const problemFor = (f: DraftProblem['field']) => problems.find(x => x.field === f)?.message;

  const category = categories.find((c: any) => c.id === draft.categoryId);

  const save = async () => {
    const found = validateDraft(draft);
    setProblems(found);
    if (found.length > 0) return;
    setBusy(true);
    try {
      const id = await saveDraft(store as SyncStore, draft, target.id);
      if (store === 'tasks' && lists.length > 0 && listId !== existingListId) {
        // General is the ABSENCE of a list, so choosing it CLEARS the field
        // rather than storing the word: every task written before lists existed
        // is on General by having no `listId` at all, and the two have to mean
        // the same thing or the same tasks would answer to two different ids.
        await edit('tasks', id, {
          listId: !listId || listId === GENERAL_LIST_ID ? undefined : listId,
        });
      }
      onClose();
    } catch (err) {
      Alert.alert('Could not save', err instanceof Error ? err.message : String(err));
      setBusy(false);
    }
  };

  const confirmDelete = () => {
    Alert.alert(
      draft.recur ? 'Delete the whole series?' : 'Delete this?',
      draft.recur
        ? 'Every occurrence will go, on this phone and on your PC.'
        : 'It will be removed from this phone and from your PC.',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: () => void (async () => {
            try {
              await removeItem(target.store as SyncStore, target.id!);
              onClose();
            } catch (err) {
              Alert.alert('Could not delete', err instanceof Error ? err.message : String(err));
            }
          })(),
        },
      ],
    );
  };

  return (
    <View style={{ flex: 1, backgroundColor: p.scrim }}>
      {/* Tapping anywhere off the sheet closes it. No pressed state: it is an
          invisible dismiss layer, and dimming the whole screen on touch would
          be a flash that means nothing. */}
      <Pressable
        unstable_pressDelay={PRESS_DELAY} style={StyleSheet.absoluteFill} onPress={onClose} accessibilityLabel="Close" />

      {/*
        THE SHEET IS NAILED TO THE BOTTOM, not merely the last thing in a column.

        It used to be `justifyContent: 'flex-end'` with a flexible spacer above
        it, and it did not sit flush: a band of scrim was left underneath, wide
        enough to read the tab bar through, which looked exactly like the sheet
        had been cropped. Two rounds of fixing the wrong thing went into that
        band -- the buttons were pinned, and the modal was told to cover the
        navigation bar (which turned out to be a no-op, because edge-to-edge
        already forces both translucency flags on).

        The suspect is `maxHeight: '92%'` on a parent with no height of its own:
        a percentage resolves against the parent, and this parent was sized BY
        its child, so the cap had nothing to resolve against. But the honest
        reason to write it this way is that it does not MATTER which of the
        column's assumptions was wrong. `bottom: 0` is not an opinion about
        leftover space, and the cap now resolves against the modal's own root,
        which React Native guarantees is full-screen. There is nothing left for
        a layout pass to get wrong.
      */}
      <KeyboardAvoidingView
        // 'padding' ON ANDROID TOO, now that the buttons are pinned to the
        // bottom instead of scrolling with the form. A pinned row is exactly
        // what a keyboard covers.
        //
        // This used to be left undefined on Android because the activity is
        // `adjustResize` and the window shrank on its own. Under edge-to-edge
        // it no longer reliably does, and the difference is invisible until
        // somebody types.
        //
        // Safe either way: the padding is computed as
        // `frame.y + frame.height - keyboardTop`, clamped at zero. If the
        // window DID resize, the sheet's bottom is already above the keyboard
        // and that comes out as zero, so nothing is lifted twice.
        behavior="padding"
        style={{
          position: 'absolute',
          left: 0,
          right: 0,
          bottom: 0,
          maxHeight: '92%',
        }}
      >
        <View style={{
          // Shrinkable, so the column below can be squeezed into the 92% cap
          // rather than overflowing it.
          flexShrink: 1,
          backgroundColor: p.surface,
          borderTopLeftRadius: radius.lg,
          borderTopRightRadius: radius.lg,
          borderTopWidth: 1,
          borderColor: p.line,
        }}>
          <View style={{ alignItems: 'center', paddingTop: space.sm }}>
            <View style={{ width: 40, height: 4, borderRadius: 2, backgroundColor: p.line }} />
          </View>

          {/*
            `flexShrink: 1` IS WHAT KEEPS THE BUTTONS ON SCREEN.

            A ScrollView has no height of its own; it takes its content's. Inside
            a box capped at 92% of the screen that means it claimed the full
            height of the form and pushed the pinned row below the sheet's own
            bounds, where it was clipped. The row was not missing -- it was
            drawn underneath. Scrolling, or any later re-render (the sync tick,
            about half a minute in), forced a fresh layout pass that happened to
            resolve it, which is exactly why it looked like it appeared on its
            own after a while.

            Shrinking lets the scroll area give the row its space first.
          */}
          <ScrollView
            style={{ flexShrink: 1 }}
            // Dragging the form puts the keyboard away rather than scrolling
            // underneath it, which is both what you meant and one fewer thing
            // being animated while the list moves.
            keyboardDismissMode="on-drag"
            contentContainerStyle={{
              padding: space.lg,
              // The pinned action row below owns the safe-area inset now; this
              // is only the gap between the last field and that row.
              paddingBottom: space.lg,
              gap: space.lg,
            }}
            keyboardShouldPersistTaps="handled"
          >
            <Row style={{ justifyContent: 'space-between', alignItems: 'center' }}>
              <Text variant="display">{isNew ? 'New' : 'Edit'}</Text>
              {!isNew && draft.recur ? (
                <Text variant="caption" tone="faint">↻ part of a series</Text>
              ) : null}
            </Row>

            {isNew ? (
              <Segment
                options={[{ key: 'events', label: 'Event' }, { key: 'tasks', label: 'Task' }]}
                value={store}
                onChange={next => {
                  setStore(next);
                  // A task has no end time; leaving one set would be written and
                  // then quietly ignored. And it starts all-day for the same
                  // reason a new one does, since switching the segment IS how
                  // most tasks get created.
                  if (next === 'tasks') {
                    set({ undated: true, allDay: true, endMin: null, daysSpan: undefined });
                  }
                  // Back to an event, and back to having a time: an all-day
                  // event is a real thing but it is not the common one, and
                  // inheriting the toggle from a task nobody kept is a
                  // surprise rather than a default.
                  // An event must be on a day; there is no undated event.
                  else if (draft.undated || draft.allDay) {
                    const start = Math.ceil(
                      (new Date().getHours() * 60 + new Date().getMinutes()) / 30,
                    ) * 30;
                    const safe = Math.min(23 * 60 + 30, start);
                    set({
                      undated: false,
                      allDay: false,
                      startMin: safe,
                      endMin: Math.min(24 * 60 - 1, safe + 60),
                    });
                  }
                }}
              />
            ) : null}

            <Field label={store === 'events' ? 'What is it' : 'What needs doing'}>
              <TextField
                value={draft.title}
                onChange={t => set({ title: t })}
                placeholder={store === 'events' ? 'Physics lecture' : 'Take the bins out'}
                autoFocus={isNew}
                invalid={Boolean(problemFor('title'))}
              />
              {problemFor('title') ? (
                <Text variant="caption" tone="danger">{problemFor('title')}</Text>
              ) : null}
            </Field>

            {/*
              A TASK CAN HAVE NO DAY. Most of them should not have one: "renew
              the passport" is something to get done, not something that happens
              on Wednesday, and pinning it to today means finding it apparently
              overdue tomorrow morning having never had a deadline.

              Only tasks. An event with no day is not a thing the grid can draw.
            */}
            <Field label={store === 'tasks' ? 'Day (optional)' : 'Day'}>
              <DateStrip
                value={draft.date}
                onChange={date => set({ date, undated: false })}
                allowNone={store === 'tasks'}
                none={store === 'tasks' && draft.undated === true}
                onNone={() => set({ undated: true, allDay: true, endMin: null })}
              />
            </Field>

            {/* Nothing below this belongs to a task with no day: a time needs a
                day to be on, and so does a repeat. */}
            {store === 'tasks' && draft.undated ? null : (
            <Field label="Time">
              <Toggle
                label="All day"
                hint={draft.allDay ? 'No particular time' : undefined}
                value={draft.allDay}
                onChange={allDay => set({
                  allDay,
                  startMin: allDay ? draft.startMin : (draft.startMin ?? 9 * 60),
                  endMin: allDay ? draft.endMin : (draft.endMin ?? (draft.startMin ?? 9 * 60) + 60),
                })}
              />

              {!draft.allDay ? (
                <View style={{ gap: space.sm }}>
                  <TimeRow
                    label="Starts"
                    step={interval}
                    minutes={draft.startMin}
                    onChange={m => set({
                      startMin: m,
                      endMin: draft.endMin !== null && m !== null && draft.endMin <= m
                        ? m + 60 : draft.endMin,
                    })}
                  />
                  {store === 'events' ? (
                    <TimeRow
                      label="Ends"
                      step={interval}
                      minutes={draft.endMin}
                      onChange={m => set({ endMin: m })}
                      clearable
                    />
                  ) : null}
                </View>
              ) : store === 'events' ? (
                <Row style={{ alignItems: 'center', gap: space.md }}>
                  <Text variant="body" tone="soft" style={{ flex: 1 }}>Covers</Text>
                  <Stepper
                    value={draft.daysSpan ?? 1}
                    min={1}
                    max={30}
                    onChange={n => set({ daysSpan: n })}
                    format={n => (n === 1 ? '1 day' : `${n} days`)}
                  />
                </Row>
              ) : null}

              {problemFor('time') ? (
                <Text variant="caption" tone="danger">{problemFor('time')}</Text>
              ) : null}
            </Field>
            )}

            {store === 'events' ? (
              <Field label="Category">
                <CategoryPicker
                  value={draft.categoryId}
                  onChange={id => setDraft(d => (
                    // Defaults only when composing. On an edit, choosing a
                    // category must not snap a 90-minute meeting back to 60.
                    isNew
                      ? applyCategoryDefaults(d, categories.find((c: any) => c.id === id))
                      : { ...d, categoryId: id }
                  ))}
                  categories={categories as any}
                />
              </Field>
            ) : null}

            {store === 'tasks' && lists.length > 0 ? (
              <Field label="List" hint="Which part of the board it sits on">
                <ListChips
                  options={lists}
                  value={resolveListId(listId, lists)}
                  onChange={next => setListId(next ?? undefined)}
                />
              </Field>
            ) : null}

            {/* ── Everything else, folded but stated ── */}
            <Pressable
        unstable_pressDelay={PRESS_DELAY}
              onPress={() => setMore(v => !v)}
              style={({ pressed }) => [{ paddingVertical: space.sm }, pressed ? PRESSED : null]}
            >
              <Row style={{ justifyContent: 'space-between', alignItems: 'center' }}>
                <Text variant="bodyStrong" tone="accent">{more ? 'Less' : 'More'}</Text>
                <Text variant="caption" tone="faint" numberOfLines={1} style={{ flex: 1, textAlign: 'right' }}>
                  {more ? '' : `${describeRecur(draft.recur)} · ${describeNotify(draft.notify)}`}
                </Text>
              </Row>
            </Pressable>

            {more ? (
              <View style={{ gap: space.lg }}>
                {/* A repeat is a rule about which DAYS something falls on, so
                    there is nothing for it to mean here. `buildTaskRecord`
                    drops the rule as well, rather than storing one that would
                    silently never fire. */}
                {store === 'tasks' && draft.undated ? null : (
                  <Field label="Repeat" hint={describeRecur(draft.recur)}>
                    <RepeatEditor
                      value={draft.recur}
                      date={draft.date}
                      onChange={recur => set({ recur })}
                    />
                  </Field>
                )}

                <Field label="Reminder" hint={describeNotify(draft.notify)}>
                  <ReminderEditor value={draft.notify} onChange={notify => set({ notify })} />
                </Field>

                {!draft.categoryId ? (
                  <Field label="Colour">
                    <ColourPicker
                      value={draft.colour}
                      onChange={colour => set({ colour })}
                      swatches={SWATCHES}
                    />
                  </Field>
                ) : (
                  <Field label="Colour">
                    <Row gap={space.sm} style={{ alignItems: 'center' }}>
                      <View style={{
                        width: 14, height: 14, borderRadius: 7,
                        backgroundColor: (category as any)?.color ?? p.accent,
                      }} />
                      <Text variant="caption" tone="faint">
                        From “{(category as any)?.name ?? 'category'}”
                      </Text>
                    </Row>
                  </Field>
                )}

                <Field label="Notes">
                  <TextField
                    value={draft.notes ?? ''}
                    onChange={t => set({ notes: t })}
                    placeholder="Anything worth remembering"
                    multiline
                  />
                </Field>

                {store === 'events' ? (
                  <Field label="Behaviour">
                    <Toggle
                      label="No checkbox"
                      hint="A reference point, not something to tick off"
                      value={draft.noCheckbox ?? false}
                      onChange={v => set({ noCheckbox: v })}
                    />
                    <Toggle
                      label="No duration"
                      hint="A moment rather than a span"
                      value={draft.noDuration ?? false}
                      onChange={v => set({ noDuration: v })}
                    />
                    {draft.recur ? (
                      <Toggle
                        label="Edits apply to the whole series"
                        hint={draft.locked
                          ? 'Changing one occurrence changes them all'
                          : 'Changing one occurrence splits it out on its own'}
                        value={draft.locked ?? false}
                        onChange={v => set({ locked: v })}
                      />
                    ) : null}
                  </Field>
                ) : null}
              </View>
            ) : null}

            {!isNew ? (
              <View style={{ gap: space.sm, paddingTop: space.sm }}>
                <View style={{ height: 1, backgroundColor: p.line }} />
                <Button label="Delete" variant="danger" onPress={confirmDelete} />
              </View>
            ) : null}
          </ScrollView>

          {/*
            SAVE AND CANCEL ARE PINNED, not scrolled.

            They used to be the last rows inside the ScrollView, so on a sheet
            with enough in it -- an event, which has a day strip, two time rows
            and a category picker -- they fell past the 92% height cap and were
            sliced in half by the bottom of the sheet. It read as a rendering
            fault rather than as "there is more below", because the thing cut
            off was the button you were reaching for.

            Out here they are always whole and always in the same place, and the
            content scrolls behind them. The inset padding is on this row now
            rather than on the scroll content, which is what keeps the buttons
            clear of the gesture bar.
          */}
          <View style={{
            flexDirection: 'row',
            gap: space.sm,
            paddingHorizontal: space.lg,
            paddingTop: space.md,
            paddingBottom: clearNav(insets.bottom) + space.md,
            borderTopWidth: 1,
            borderTopColor: p.line,
            backgroundColor: p.surface,
          }}>
            <Button label="Cancel" variant="secondary" onPress={onClose} style={{ flex: 1 }} />
            <Button
              label={isNew ? 'Add' : 'Save'}
              onPress={() => void save()}
              busy={busy}
              style={{ flex: 2 }}
            />
          </View>
        </View>
      </KeyboardAvoidingView>
    </View>
  );
}

/** A new item starts in the category the user marked as their default. */
function withDefaultCategory(input: DraftInput, categories: any[]): DraftInput {
  const preferred = categories?.find?.((c: any) => c?.isDefault);
  return preferred ? applyCategoryDefaults(input, preferred) : input;
}

// ─── Repeat ──────────────────────────────────────────────────────────────────

const FREQS: { key: RecurFreq; label: string }[] = [
  { key: 'daily', label: 'Day' },
  { key: 'weekly', label: 'Week' },
  { key: 'monthly', label: 'Month' },
  { key: 'yearly', label: 'Year' },
];

function RepeatEditor({ value, date, onChange }: {
  value: Recurrence | undefined;
  date: string;
  onChange: (next: Recurrence | undefined) => void;
}) {
  const p = useTheme();
  const on = Boolean(value);

  const set = (patch: Partial<Recurrence>) =>
    onChange({ freq: 'weekly', interval: 1, ...value, ...patch } as Recurrence);

  const endKind: 'never' | 'until' | 'count' =
    !value?.end ? 'never' : ('until' in value.end ? 'until' : 'count');

  return (
    <View style={{ gap: space.md }}>
      <Toggle
        label="Repeats"
        value={on}
        onChange={next => onChange(next ? { freq: 'weekly', interval: 1 } : undefined)}
      />

      {on && value ? (
        <View style={{ gap: space.md }}>
          <Row style={{ alignItems: 'center', gap: space.md }}>
            <Text variant="body" tone="soft">Every</Text>
            <Stepper
              value={Math.max(1, value.interval || 1)}
              min={1}
              max={52}
              onChange={n => set({ interval: n })}
            />
          </Row>

          <Segment
            options={FREQS}
            value={value.freq}
            onChange={freq => set({
              freq,
              // Weekday choices only mean anything for a weekly rule; carrying
              // them onto a monthly one would store a rule nothing can read.
              byWeekday: freq === 'weekly' ? value.byWeekday : undefined,
            })}
          />

          {value.freq === 'weekly' ? (
            <WeekdayPicker
              value={value.byWeekday ?? []}
              onChange={byWeekday => set({ byWeekday: byWeekday.length ? byWeekday : undefined })}
            />
          ) : null}

          <View style={{ gap: space.sm }}>
            <Segment
              options={[
                { key: 'never', label: 'Forever' },
                { key: 'until', label: 'Until' },
                { key: 'count', label: 'Times' },
              ]}
              value={endKind}
              onChange={kind => {
                if (kind === 'never') return set({ end: undefined });
                if (kind === 'count') return set({ end: { count: 10 } });
                return set({ end: { until: addDays(date, 7 * 12) } });
              }}
            />

            {endKind === 'count' && value.end && 'count' in value.end ? (
              <Stepper
                value={value.end.count}
                min={1}
                max={365}
                onChange={n => set({ end: { count: n } })}
                format={n => `${n} time${n === 1 ? '' : 's'}`}
              />
            ) : null}

            {endKind === 'until' && value.end && 'until' in value.end ? (
              <DateStrip
                value={value.end.until}
                onChange={until => set({ end: { until } })}
                from={date}
                days={28}
              />
            ) : null}
          </View>
        </View>
      ) : null}
    </View>
  );
}

function WeekdayPicker({ value, onChange }: {
  value: Weekday[]; onChange: (next: Weekday[]) => void;
}) {
  const p = useTheme();
  const days: Weekday[] = [0, 1, 2, 3, 4, 5, 6];

  return (
    <Row gap={space.xs}>
      {days.map(d => {
        const on = value.includes(d);
        return (
          <Pressable
        unstable_pressDelay={PRESS_DELAY}
            key={d}
            onPress={() => onChange(on ? value.filter(x => x !== d) : [...value, d])}
            accessibilityRole="button"
            accessibilityLabel={weekdayName(d)}
            accessibilityState={{ selected: on }}
            style={({ pressed }) => [{
              flex: 1, height: 40,
              alignItems: 'center', justifyContent: 'center',
              borderRadius: radius.sm,
              backgroundColor: on ? p.accent : p.surfaceAlt,
              borderWidth: 1,
              borderColor: on ? p.accent : p.line,
            }, pressed ? PRESSED : null]}
          >
            <Text
              variant="caption"
              style={{ color: on ? p.accentInk : p.inkSoft, fontWeight: '700' }}
            >
              {weekdayName(d).slice(0, 1)}
            </Text>
          </Pressable>
        );
      })}
    </Row>
  );
}

// ─── Reminder ────────────────────────────────────────────────────────────────

function ReminderEditor({ value, onChange }: {
  value: any; onChange: (next: any) => void;
}) {
  const p = useTheme();

  const mode: 'default' | 'off' | 'custom' =
    !value ? 'default' : (value.enabled === false ? 'off' : 'custom');

  const rules: { id: string; offsetMin: number }[] = value?.rules ?? [];

  return (
    <View style={{ gap: space.md }}>
      <Segment
        options={[
          { key: 'default', label: 'Default' },
          { key: 'off', label: 'Off' },
          { key: 'custom', label: 'Custom' },
        ]}
        value={mode}
        onChange={next => {
          // ABSENT means inherit — from the category, then the global default.
          // That is why an item created before reminders existed still gets
          // them, so "Default" must clear the field rather than write a copy.
          if (next === 'default') return onChange(undefined);
          if (next === 'off') return onChange({ enabled: false, rules: [], priority: 'normal' });
          return onChange({
            enabled: true,
            rules: [{ id: 'r0', offsetMin: 0 }],
            priority: value?.priority ?? 'normal',
          });
        }}
      />

      {mode === 'default' ? (
        <Text variant="caption" tone="faint">
          Follows the category, or your global setting if it has none.
        </Text>
      ) : null}

      {mode === 'custom' ? (
        <View style={{ gap: space.sm }}>
          {rules.map((rule, i) => (
            <Row key={rule.id ?? i} gap={space.sm} style={{ alignItems: 'center' }}>
              <View style={{ flex: 1 }}>
                <OffsetPicker
                  value={rule.offsetMin}
                  onChange={offsetMin => onChange({
                    ...value,
                    rules: rules.map((r, j) => (j === i ? { ...r, offsetMin } : r)),
                  })}
                />
              </View>
              {rules.length > 1 ? (
                <Pressable
        unstable_pressDelay={PRESS_DELAY}
                  onPress={() => onChange({ ...value, rules: rules.filter((_, j) => j !== i) })}
                  hitSlop={space.sm}
                  accessibilityLabel="Remove this reminder"
                  style={({ pressed }) => [{ width: 32, height: 32, alignItems: 'center', justifyContent: 'center' }, pressed ? PRESSED : null]}
                >
                  <Text variant="body" tone="faint">✕</Text>
                </Pressable>
              ) : null}
            </Row>
          ))}

          {rules.length < 4 ? (
            <Pressable
        unstable_pressDelay={PRESS_DELAY}
              onPress={() => onChange({
                ...value,
                rules: [...rules, { id: `r${Date.now()}`, offsetMin: -15 }],
              })}
              style={({ pressed }) => [{ paddingVertical: space.sm }, pressed ? PRESSED : null]}
            >
              <Text variant="caption" tone="accent">+ Another reminder</Text>
            </Pressable>
          ) : null}

          <Toggle
            label="Urgent"
            hint="Keeps alerting until you deal with it"
            value={value?.priority === 'critical'}
            onChange={v => onChange({ ...value, priority: v ? 'critical' : 'normal' })}
          />
        </View>
      ) : null}
    </View>
  );
}

function OffsetPicker({ value, onChange }: {
  value: number; onChange: (next: number) => void;
}) {
  const p = useTheme();
  return (
    <ScrollView
      horizontal
      // Android needs telling that this belongs to a bigger scroller. Without
      // it a vertical drag that happens to START on this strip is swallowed --
      // the sheet does not move, the strip does not move, and it reads as the
      // page being stuck rather than as a gesture landing on the wrong view.
      nestedScrollEnabled
      showsHorizontalScrollIndicator={false}
      contentContainerStyle={{ gap: space.xs, paddingRight: space.lg }}
    >
      {OFFSET_PRESETS_TIMED.map(off => {
        const on = off === value;
        return (
          <Pressable
        unstable_pressDelay={PRESS_DELAY}
            key={off}
            onPress={() => onChange(off)}
            accessibilityRole="button"
            accessibilityState={{ selected: on }}
            style={({ pressed }) => [{
              paddingHorizontal: space.md, height: 36,
              alignItems: 'center', justifyContent: 'center',
              borderRadius: radius.pill,
              backgroundColor: on ? p.accentSoft : p.surfaceAlt,
              borderWidth: 1, borderColor: on ? p.accent : p.line,
            }, pressed ? PRESSED : null]}
          >
            <Text variant="caption" tone={on ? 'accent' : 'soft'}>
              {offsetLabel(off)}
            </Text>
          </Pressable>
        );
      })}
    </ScrollView>
  );
}

// ─── Time and date ───────────────────────────────────────────────────────────

function TimeRow({ label, minutes, onChange, clearable, step = 15 }: {
  label: string;
  minutes: number | null;
  onChange: (next: number | null) => void;
  clearable?: boolean;
  /** The snap interval, from this device's settings. */
  step?: number;
}) {
  const p = useTheme();

  const nudge = (delta: number) => {
    const base = minutes ?? 9 * 60;
    // Snapped to the interval, not merely moved by it: a time of 09:07 nudged by
    // fifteen should land on 09:15, not 09:22. Otherwise a single off-grid value
    // keeps every later step off-grid too.
    const raw = base + delta;
    const snapped = delta > 0
      ? Math.ceil(raw / step) * step
      : Math.floor(raw / step) * step;
    onChange(((snapped % 1440) + 1440) % 1440);
  };

  return (
    <Row style={{ alignItems: 'center', justifyContent: 'space-between' }}>
      <Text variant="body" tone="soft" style={{ width: 58 }}>{label}</Text>

      <Row gap={space.xs} style={{ alignItems: 'center' }}>
        {/*
          THE SLOT IS RESERVED ON BOTH ROWS, empty on the one that cannot be
          cleared. That is the whole trick: "Ends" carries a Clear and "Starts"
          does not, and while that button sat on the RIGHT it made the Ends row
          wider, pushing its minus, its time and its plus left of the ones
          directly above them. Two controls that do the same thing, a centimetre
          apart, on consecutive lines.

          Reserving the space on the left instead lines the two steppers up
          exactly, and puts Clear on the outside where it is furthest from the
          buttons you actually press.
        */}
        <View style={{ width: CLEAR_SLOT, alignItems: 'flex-end' }}>
          {clearable ? (
            <Pressable
        unstable_pressDelay={PRESS_DELAY}
              onPress={() => onChange(minutes === null ? 10 * 60 : null)}
              hitSlop={space.sm}
              accessibilityRole="button"
              style={({ pressed }) => [
                { paddingHorizontal: space.xs, height: HIT, justifyContent: 'center' },
                pressed ? PRESSED : null,
              ]}
            >
              <Text variant="caption" tone="accent">{minutes === null ? 'Set' : 'Clear'}</Text>
            </Pressable>
          ) : null}
        </View>

        <Step label="−" onPress={() => nudge(-step)} onLongPress={() => nudge(-60)} />
        <Pressable
        unstable_pressDelay={PRESS_DELAY}
          onPress={() => (minutes === null ? onChange(9 * 60) : undefined)}
          style={({ pressed }) => [{
            minWidth: 88, height: HIT,
            paddingHorizontal: space.md,
            borderRadius: radius.md,
            borderWidth: 1, borderColor: p.line,
            backgroundColor: p.surfaceAlt,
            alignItems: 'center', justifyContent: 'center',
          }, pressed ? PRESSED : null]}
        >
          <Text variant="bodyStrong" tone={minutes === null ? 'faint' : 'ink'}>
            {minutes === null ? 'None' : toTimeString(minutes)}
          </Text>
        </Pressable>
        <Step label="+" onPress={() => nudge(step)} onLongPress={() => nudge(60)} />
      </Row>
    </Row>
  );
}

/**
 * How much room the Clear/Set button is given.
 *
 * Wide enough for "Clear" at caption size with a little air, and identical on
 * the row that has no button, because being identical is the entire point.
 */
const CLEAR_SLOT = 52;

function Step({ label, onPress, onLongPress }: {
  label: string; onPress: () => void; onLongPress: () => void;
}) {
  const p = useTheme();
  return (
    <Pressable
        unstable_pressDelay={PRESS_DELAY}
      onPress={onPress}
      onLongPress={onLongPress}
      delayLongPress={300}
      accessibilityRole="button"
      accessibilityLabel={label === '+' ? 'Later' : 'Earlier'}
      style={({ pressed }) => ({
        width: 42, height: HIT,
        borderRadius: radius.md,
        alignItems: 'center', justifyContent: 'center',
        backgroundColor: pressed ? p.accentSoft : p.surfaceAlt,
        borderWidth: 1, borderColor: p.line,
      })}
    >
      <Text variant="title" tone="soft">{label}</Text>
    </Pressable>
  );
}

function DateStrip({ value, onChange, from, days = 14, allowNone, none, onNone }: {
  value: string;
  onChange: (date: string) => void;
  from?: string;
  days?: number;
  /** Offer a "No date" chip at the head of the strip. Tasks only. */
  allowNone?: boolean;
  /** Whether that chip is the one currently chosen. */
  none?: boolean;
  onNone?: () => void;
}) {
  const p = useTheme();
  const today = ymd(new Date());
  const start = from ?? today;
  /**
   * The days on offer, and always the one already chosen.
   *
   * The strip runs a fixed number of days from `from`, which is fine for a
   * fresh rule but wrong for an existing one: a repeat that ends in two years
   * had its own date sitting outside the window, so the strip showed nothing
   * selected and the date read as unset. It is appended when it falls outside,
   * so what is stored is always visible and always shown as chosen.
   */
  const list = useMemo(() => {
    const days_ = Array.from({ length: days }, (_, i) => addDays(start, i));
    if (value && !days_.includes(value)) {
      days_.push(value);
      days_.sort();
    }
    return days_;
  }, [start, days, value]);

  return (
    <ScrollView
      horizontal
      // Android needs telling that this belongs to a bigger scroller. Without
      // it a vertical drag that happens to START on this strip is swallowed --
      // the sheet does not move, the strip does not move, and it reads as the
      // page being stuck rather than as a gesture landing on the wrong view.
      nestedScrollEnabled
      showsHorizontalScrollIndicator={false}
      contentContainerStyle={{ gap: space.xs, paddingRight: space.lg }}
    >
      {/* First, and the width of two day chips, because it is a real answer
          rather than an escape from the question. */}
      {allowNone ? (
        <Pressable
          onPress={onNone}
          accessibilityRole="button"
          accessibilityState={{ selected: none === true }}
          accessibilityLabel="No date"
          unstable_pressDelay={PRESS_DELAY}
          style={({ pressed }) => [{
            minWidth: 84,
            paddingVertical: space.sm,
            paddingHorizontal: space.sm,
            borderRadius: radius.md,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: none ? p.accentSoft : p.surfaceAlt,
            borderWidth: 1,
            borderColor: none ? p.accent : p.line,
          }, pressed ? PRESSED : null]}
        >
          <Text variant="bodyStrong" tone={none ? 'accent' : 'soft'}>No date</Text>
          <Text variant="caption" tone="faint">anytime</Text>
        </Pressable>
      ) : null}

      {list.map(date => {
        const on = !none && date === value;
        const d = new Date(`${date}T00:00:00`);
        return (
          <Pressable
        unstable_pressDelay={PRESS_DELAY}
            key={date}
            onPress={() => onChange(date)}
            accessibilityRole="button"
            accessibilityState={{ selected: on }}
            style={({ pressed }) => [{
              minWidth: 54, paddingVertical: space.sm, paddingHorizontal: space.sm,
              borderRadius: radius.md, alignItems: 'center', gap: 1,
              backgroundColor: on ? p.accentSoft : p.surfaceAlt,
              borderWidth: 1, borderColor: on ? p.accent : p.line,
            }, pressed ? PRESSED : null]}
          >
            <Text variant="caption" tone={on ? 'accent' : 'faint'} style={{ fontSize: 11 }}>
              {d.toLocaleDateString(undefined, { weekday: 'short' })}
            </Text>
            <Text variant="bodyStrong" tone={on ? 'accent' : 'ink'}>{d.getDate()}</Text>
            <Text variant="caption" tone={on ? 'accent' : 'faint'} style={{ fontSize: 10 }}>
              {date === today ? 'today' : d.toLocaleDateString(undefined, { month: 'short' })}
            </Text>
          </Pressable>
        );
      })}
    </ScrollView>
  );
}
